baseURL = 'https://twigsite.ca/'
languageCode = 'en-us'
title = 'Twig Site'

disableKinds = ['taxonomy', 'term', 'sitemap', 'rss']
uglyURLs = true
cleanDestinationDir = true

[markup.goldmark.renderer]
    unsafe = true
[markup.goldmark.renderHooks.link]
    useEmbedded = 'fallback'
[markup.goldmark.renderHooks.image]
    useEmbedded = 'fallback'